sonar.projectName=nestjs-cinema
sonar.projectVersion=1.0
sonar.host.url=https://sonarcloud.io
sonar.organization=cinema-compass

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.e2e-spec.ts

sonar.language=ts
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.ts.eslint.reportPaths=eslint-report.json
sonar.exclusions=**/node_modules/**,**/dist/**
